### ISSUE TITLE
As a (CLI) user, I want a clean graph from OSM download

### ISSUE THREAD

**Issue by frederique-hub** [Deltares/ra2ce#104]
- [x] I can use the function without needing to provide a configuration file
- [x] I can download graphs from OSM with a geojson polygon as input
- [ ] I have options to simplify the graph  https://github.com/Deltares/ra2ce/issues/144
- [ ] https://github.com/Deltares/ra2ce/issues/110
- [x] Write (unit) tests for the newly created methods.
- [x] Improve modularity of `network_osm_download` in `networks.py`
Desired implementation:
Create a static method whose signature should look something like:
```python
@staticmethod
    def get_clean_graph_from_osm_download(polygon: BaseGeometry, network_type: str, road_types: str) -> Graph:
```
Where the input arguments are the used `self.` properties currently used in the `network_osm_download` until (and including) the `logging.info` (polygon (**converted fom** `self.config["network"]["polygon"][0]`), network_type ( `self.config["network"]["network_type"]`) and road_types ( `self.config["network"]["road_types"]`), the return type should be the type of the current parameter `graph_complex` in the `network_osm_download` method.

**Comment by sahand-asgarpour** [comment]
Please note that the performed (ticked-off) tasks are performed without creating the cleaning/simplifying features. 

Further alignment and specification can help create such functions.
