### ISSUE TITLE
As a developer, I want to create objects without file dependencies

### ISSUE THREAD

**Issue by frederique-hub** [Deltares/ra2ce#106]
This is an ongoing issue until the network module is finalized.
@Carsopre maybe you can add more info if necessary.

**Comment by xldeltares** [comment]
As a potential user of ra2ce network module as dependencies, I would like to have more flexibility in the shapely and gdal dependencies for easier installation. especially that shapely had a major update to 2.0.0 last year.

**Comment by Carsopre** [comment]
This issue has been address in #181, #42, #107 and soon in #41 .
