### ISSUE TITLE
As a developer, I want to know what functions we are going to make (name, input, output)

### ISSUE THREAD

**Issue by frederique-hub** [Deltares/ra2ce#114]
I (Frederique) imagine this as a list of function names that are available to the users of ra2ce, including input arguments and types and output. It would be great to make this list together before starting the work on the network module.

**Network Module**

Retrieving data (lower-level functions):

`get_graph_from_osm_download(polygon: BaseGeometry, network_type: str, road_types: str, simplify: bool) -> Graph`
`get_graph_from_file(file: Path) -> Graph` (can be multiple file types)
`get_graph_from_files(files: List[Path]) -> Graph` (can be multiple file types and files)
`read(file: Path) -> GeoDataFrame`

Harmonizing data:
`rename(columns: dict)` This function can be used to rename the attributes to names used internally in RA2CE (e.g. 'geoms' :'geometry') 

_Before the graph is made_: Cleaning vector data (shapefile, geopackage) to make a good graph

`snapping(gdf: GeoDataFrame, snap_threshold: float) -> GeoDataFrame`
`pruning(gdf: GeoDataFrame, prune_threshold: float) -> GeoDataFrame`
`update_geometry_attributes(gdf: GeoDataFrame, attributes: List[str]) -> GeoDataFrame` (updates the lengths of the line segments and other attributes that the user might input)
`merge_sequential_lines(gdf: GeoDataFrame, exclude: dict) -> GeoDataFrame` the exclude argument is a dictionary with attribute-list of value pairs to exclude from the merging of the lines (e.g. {'type': ['bridge', 'tunnel']}
`split_at_intersections(gdf: GeoDataFrame) -> GeoDataFrame`

_After the graph is made_: Simplifying graph (all functions return a cleaned version of the graph) --> Check if the simplifying functions can be used from OSMNX:

``

**Comment by ThomasBles** [comment]
This is about defining what the exact requirements are regarding functions for the issues
