### ISSUE TITLE
As a (CLI) user, I want to have examples of use cases

### ISSUE THREAD

**Issue by frederique-hub** [Deltares/ra2ce#115]
- [x] Create a network from OSM
- [x] Run a single link redundancy analysis
- [x] Run an Origin- closest Destination analysis
- [x] Run a direct damage assessment @sahand-asgarpour 
- [x] Run an all Origins to all Destinations analysis
- [ ] Analyse measures: TODO after adaptation
- [ ] Run an analysis with return period flood maps: linked to damages/losses @sahand-asgarpour 
- [x] Run a single_link_losses analysis @sahand-asgarpour 
- [x] Run a multi_link_losses analysis @sahand-asgarpour

**Comment by ArdtK** [comment]
@sahand-asgarpour can we have a look at this issue? Today we discussed in the standup and it depends on several things your are/will be working on. Preferably we close this issue and add the tasks to the work it relates to (e.g. losses).
