### ISSUE TITLE
As a developer, I want to a repository to place big data to use for tests and examples

### ISSUE THREAD

**Issue by frederique-hub** [Deltares/ra2ce#117]
Using SVN

**Comment by Carsopre** [comment]
test data can be placed here:
https://repos.deltares.nl/repos/GFS_incubator/branches/ra2ce_test_data 
Tests using this data need to be appointed with the specific marker '@external_test'

**Comment by Carsopre** [comment]
Extended `contributing` documentation regarding how to write tests / documentation, reduced initial README to avoid repeating information already described in the github pages site.
-     Created new marker for running tests located outside our repository.
-     Created test case collector from a non-version-controlled directory.
-     Created TeamCity configuration for running said external cases.
