### ISSUE TITLE
As a (CLI) user, I want to be able to track which network segments relate to which graph segments

### ISSUE THREAD

**Issue by frederique-hub** [Deltares/ra2ce#126]
When assessing direct and indirect damage for the same network. E.g., when the direct damage assessment network is cut into 100 m segments and the indirect damage graph is segmented from intersection to intersection, I want to know the ID relations between those segments. 

Code is already implemented for this in RA2CE, this functionality needs to be present in the renewed network module.

**Comment by sahand-asgarpour** [comment]
This is traceable by the attribute rfid_c in the network file, and rfid in the graph file.
