### ISSUE TITLE
As a user, I want to have a compiled version of RA2CE

### ISSUE THREAD

**Issue by frederique-hub** [Deltares/ra2ce#140]
Generate all the possible artifacts from the `master` branch of `ra2ce`:
- [x] Create a TeamCity configuration with all possible artifacts.
- [x] Wheel (dll) via `poetry build`
- [x] Exe via `make` file.

**Comment by Carsopre** [comment]
TeamCity configuration can be found here:
https://dpcbuild.deltares.nl/buildConfiguration/Ra2ce_Ra2ceContinuousIntegrationBuild_BuildDeliverables?branch=&buildTypeTab=overview

**Comment by Carsopre** [comment]
Exe can be built with `poetry run build-cli` which uses a `pyinstaller` script. This step is now added in the configuration build earlier mentioned and generates later on a new artifact.

**Comment by Carsopre** [comment]
This should be working already, it might be possible that some packages are not included during installation. If that happens then we can extend the script in `scripts\make_exe.py` to include them

**Comment by Carsopre** [comment]
Apparently tc (and also locally) every now and then it fails due to what seems to be a permissions issue. For now we can leave it as it is knowing we can locally generate the exe and distribute it / attach it to a release whenever needed.
