### ISSUE TITLE
Implement the new multi-link isolated locations code into RA2CE

### ISSUE THREAD

**Issue by frederique-hub** [Deltares/ra2ce#147]
During the analysis, we want to add new attributes for those locations who remain isolated because of surrounding flooded areas.

- [x] Extend current analysis_indirect.py with the changes from the Bolivia project that include the aforementioned extra attributes.

- [x] Extend hazard with a new function to retrieve the locations with the new attributes.
- [x] Extend network to have its own cleanup method (and extend it: https://github.com/Deltares/ra2ce/issues/144), otherwise just read the network as is: 
```    def cleanup(self, config_dict: dict):
        _cleanup_dict = config_dict.get("cleanup", None)
        if not _cleanup_dict:
            return
        ...
```
- [x] Verify that the tests are running and still giving valid results.
- [ ] Potentially extend the test suite with an example of multi-link isolated locations. (unit test with dummy data)

**Comment by xldeltares** [comment]
trying to reproduce Bolivia test case:
- [ ] add dependency: pygeos to pyproject.toml
- [ ] Check crs of the network:
UserWarning: Geometry is 
in a geographic CRS. Results from 'sjoin_nearest' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  warnings.warn(
2023-07-13 02:29:06 PM - [hazard.py:948] - root - WARNING - Hazard crs EPSG:32720 and location crs epsg:4326 are inconsistent,
                                                we try to reproject the location crs
2023-07-13 02:29:06 PM - [hazard.py:955] - root - INFO - Gdf extent before reprojecting: [-63.2501     -17.90435596 -63.0551     -17.6638    ]

**Comment by xldeltares** [comment]
With regard to Extend hazard with a new function to retrieve the locations with the new attributes, the following lines are relevant:

```
# spatial join the locations with the network edges
logging.info("Spatial join the locations with the network edges")
edges = self.graphs["base_network"]
edges["edge_fid"] = [f"{na}_{nb}" for na, nb in edges[["node_A", "node_B"]].values]
locations = gpd.sjoin_nearest(locations, edges, how="left", distance_col = "edges_distance")
if locations["edges_distance"].isna().sum() > 0:
    logging.warning("Some locations are not connected to the network. These locations will be removed from the isolation analysis.")
```

I propose to later move `edges["edge_fid"] = [f"{na}_{nb}" for na, nb in edges[["node_A", "node_B"]].values]` to network.py as a universal edge attribute during refactor: https://github.com/Deltares/ra2ce/issues/114

**Comment by xldeltares** [comment]
Need fix: UserWarning: Setting nodata to -999; specify nodata explicitly
  warnings.warn("Setting nodata to -999; specify nodata explicitly")

- [ ] message due to no data value not set for `zonal_stats` function

**Comment by xldeltares** [comment]
Need help from @Carsopre to set up Bolivia test case on svn.
