### ISSUE TITLE
Improvements that could simplify the use network module from external package

### ISSUE THREAD

**Issue by xldeltares** [Deltares/ra2ce#172]
I made a first attempt calling the osm network wrapper to create a network in my function (similar to a Jupiter notebook setting), where I don’t give a ini file but populate the wrapper on-the-fly. It was very easy to use with the new architecture and has been working really well, very nice! In the meantime, I figured that process could even be simplified for the following points

**Describe the issue** 

1.	The   `OsmNetworkWrapper.polygon_path` requires a file path,  would it make sense to also support polygon geometryor geodataframe? For now in my function, I approached it by write the polygon as a temp file first. It works but that is not very efficient. 
2.	There is also a property called `OsmNetworkWrapper.output_graph_dir`, which points to the static folder. In my code, I don’t have the need to write the network (because of further processing), so I wonder if the writing funcs can be more separated from the network creation for convenience?
3.	For the dependencies, for now we are being very strict on the `gdal` version, which makes it difficult to install together with other geo-processing tools. Besides, `shapely` update to > 2.0.0 could be beneficial, as previously identified. Further more, besides the main dependencies, I also needed to install package `geopy`, `geojson` and `tqdm`, while the funcs using these packages also exist in `geopandas` and `itertools`. Would it be an idea to replace these packages? (also reported in issue #106)
4. documentation for the static functions would be very handy.

**How to reproduce** 
```
# get graph from osm data
# create an emtpy wrapper
_network_config_data = NetworkConfigData()
_osm_network_wrapper = OsmNetworkWrapper(_network_config_data)
# configure wrapper properties
_osm_network_wrapper.is_directed = True
_osm_network_wrapper.network_type = network_type
_osm_network_wrapper.road_types = road_types
_osm_network_wrapper.polygon_path = _get_temp_polygon_path()
_osm_network_wrapper.output_graph_dir = _get_temp_output_graph_dir()
# download from osm and perform cleaning (drop_duplicates, add_missing_geoms_graph, snap_nodes_to_nodes)
_osm_graph = _osm_network_wrapper.get_clean_graph_from_osm()
```

**Additional info**
Here is a snapshot of the [code using network module]([hydromt_delft3dfm/hydromt_delft3dfm/workflows/urbansewernetwork.py at urbansewer/40-setup_network_from_openstreetmap · Deltares/hydromt_delft3dfm (github.com)](https://github.com/Deltares/hydromt_delft3dfm/blob/urbansewer/40-setup_network_from_openstreetmap/hydromt_delft3dfm/workflows/urbansewernetwork.py#L35)

**Comment by MatthiasHauthDeltares** [comment]
this [PR](https://github.com/Deltares/ra2ce/pull/558l) should alleviate restriction on GDAL
