### ISSUE TITLE
Update geo dependencies

### ISSUE THREAD

**Issue by Carsopre** [Deltares/ra2ce#180]
We should address (after the launch) the update of dependencies consisting of:

- [x] Upgrade `shapely` > 2.0.0, this will probably imply updates in the code due to new API.

Replace all unnecessary dependencies (`geopy`, `geojson` and `tqdm` are included in `geopandas` and `itertools`) (see #172 or #106).
- [x] Replace `geojson` usage with `geopandas`.
- [ ] #188
- [ ] #189

Improve `GDAL` and `OSMnx` dependencies:
- [x] Check latest `gdal` dependencies.
- [ ] #191

**Comment by Carsopre** [comment]
`fiona` dependency has been removed as we run now `geopandas.read_file` using `engine="pyogrio"`.

**Comment by frederique-hub** [comment]
Maybe that is why Lieke has a Fiona Driver error?
