### ISSUE TITLE
Replace `geopy` usage with `geopandas`.

### ISSUE THREAD

**Issue by Carsopre** [Deltares/ra2ce#188]
Can we replace `geopy` functionality with `geopandas`? 
The only method at the moment using `geopy` (and therefore why we require to install the dependency it's in `network_utils.get_distance`.
Consider replacing the content of the method with similar logic using `geopandas`.

**Comment by frederique-hub** [comment]
Good idea! I guess `geopandas` has the same functionality

**Comment by Carsopre** [comment]
It is not worth replacing the single call we make to `geopy.distance` as it's alternative will look something as the code that can be found here: https://autogis-site.readthedocs.io/en/2019/notebooks/L2/calculating-distances.html . 
This justification will be reflected in a new documentation section called Design Principles.
