### ISSUE TITLE
Network from a `.shp` file and a primary file (in the `.ini` file).

### ISSUE THREAD

**Issue by Carsopre** [Deltares/ra2ce#194]
Network from a `.shp` file and a primary file (in the `.ini` file).
- [x] Documentation is present.
- [x] Use cases / examples / test cases are present.

**Comment by LiekeMeijer** [comment]
You can do this easily if you do not use the clean up functionality. When I had the merge_lines clean up functionality set to true I got the error as reported in iossue #210

**Comment by LiekeMeijer** [comment]
The resulting graph has removed all of my interesting attributes that were originally in the shapefile such as the road types. This is the only information left: 

![Image](https://github.com/Deltares/ra2ce/assets/112695332/4f60ef11-6bb1-48a4-b2e1-b3d09c3624f5)

**Comment by Carsopre** [comment]
@LiekeMeijer 's bug might collide with the corrent approach of combining / merging networks as described by @frederique-hub .
