### ISSUE TITLE
Network from a `osm download` as specified in the `.ini` file (@sahand-asgarpour  and @LiekeMeijer  have ideas on this).

### ISSUE THREAD

**Issue by Carsopre** [Deltares/ra2ce#195]
Network from a `osm download` as specified in the `.ini` file (@sahand-asgarpour  and @LiekeMeijer  have ideas on this).
- [x] Documentation is present.
- [x] Use cases / examples / test cases are present.

**Comment by LiekeMeijer** [comment]
I updated the ra2ce_basics notebook. I created the folder structure that can be used to execute this notebook (ra2ce/examples/data/base_network) which contains map.geojson to set up a basic network and the .ini files to execute it.
