### ISSUE TITLE
Indirect analysis, further break down in

### ISSUE THREAD

**Issue by Carsopre** [Deltares/ra2ce#200]
- [ ] Do the following for the analysis listed bellow: 
- [x] Documentation is present,
- [x] Examples work in the example notebooks
- [ ] #211

Further break down in:
- [x] #208
- [x] origin-destination (with / without hazard): @sahand-asgarpour
- [x] single-link redundancy: @LiekeMeijer

**Comment by sahand-asgarpour** [comment]
- @sahand-asgarpour clips the OD data for the Beira example.

**Comment by LiekeMeijer** [comment]
Updated single_link redundancy notebook. Created folder setup for the example in the ra2ce/examples/data/single_link_redun folder.
