### ISSUE TITLE
Check Binder environment works

### ISSUE THREAD

**Issue by Carsopre** [Deltares/ra2ce#202]
- [x] single link redundancy
- [x] race_basics
- [x] race_basics_fromshp
- [x] origin_destination_analysis 
- [x] optimal_route_origin_destination
- [x] isolated_locations 
- [x] hazard_overlay

**Comment by frederique-hub** [comment]
![image](https://github.com/Deltares/ra2ce/assets/72015981/9c9436d0-bd37-4b45-b5aa-0d1fbaf6d42c)

**Comment by MatthiasHauthDeltares** [comment]
Note: make sure that the path are correct in the .ipynb.
root_dir = Path().parent / "data" / "isolated_locations"  is good
root_dir = Path (r'.\\data\\hazard_overlay')   is not good
