### ISSUE TITLE
origin-closest destination (with / without hazard):  @sahand-asgarpour

### ISSUE THREAD

**Issue by sahand-asgarpour** [Deltares/ra2ce#208]

**Comment by sahand-asgarpour** [comment]
- [ ]   #209

**Comment by mjevanmarle** [comment]
Same as 209. Check with Sahand

**Comment by sahand-asgarpour** [comment]
This is linked to #209 which is ticked off. The notebook also runs without any hazard so this issue and #209 can be closed.
