### ISSUE TITLE
Creating network from SHP: 'ERROR: GDF object has no attribute 'append'

### ISSUE THREAD

**Issue by LiekeMeijer** [Deltares/ra2ce#210]
AttributeError                            Traceback (most recent call last)
[~\AppData\Local\Temp\ipykernel_10932\38322887.py](https://file+.vscode-resource.vscode-cdn.net/c%3A/python/ra2ce/examples/~/AppData/Local/Temp/ipykernel_10932/38322887.py) in ?()
      1 handler = Ra2ceHandler(network=network_ini, analysis=None)
----> 2 handler.configure()

[C:\python\ra2ce\ra2ce\ra2ce_handler.py](file:///C:/python/ra2ce/ra2ce/ra2ce_handler.py) in ?(self)
     70     def configure(self) -> None:
---> 71         self.input_config.configure()

[C:\python\ra2ce\ra2ce\configuration\config_wrapper.py](file:///C:/python/ra2ce/ra2ce/configuration/config_wrapper.py) in ?(self)
     77     def configure(self) -> None:
     78         if self.network_config:
---> 79             self.network_config.configure_network()
     80             self.network_config.configure_hazard()
     81         if self.analysis_config:
     82             self.analysis_config.configure()

[C:\python\ra2ce\ra2ce\graph\network_config_wrapper.py](file:///C:/python/ra2ce/ra2ce/graph/network_config_wrapper.py) in ?(self)
    154     def configure_network(self) -> None:
    155         network = Network(self.config_data, self.files)
--> 156         self.graphs = network.create()

[C:\python\ra2ce\ra2ce\graph\networks.py](file:///C:/python/ra2ce/ra2ce/graph/networks.py) in ?(self)
    215         network_gdf = None
...
   5987         ):
   5988             return self[name]
-> 5989         return object.__getattribute__(self, name)

**AttributeError: 'GeoDataFrame' object has no attribute 'append'**

**Comment by LiekeMeijer** [comment]
This happened when using clean up functionality, I had merge_lines set to true. This increased computation time from 10 seconds to 40 minutes and resulted in an error eventually. I.e.: you can create a network but the clean-up functionality needs to be well-documented and tested...

**Comment by Carsopre** [comment]
Because we do not have a clear overview on how to reproduce the steps we don't know whether this is a failure because of an outdated jupyter notebook or a bug in the ra2ce code. Therefore this issue can be closed.
