### ISSUE TITLE
It should be possible to run ra2ce multiple times (ra2ce batch run)

### ISSUE THREAD

**Issue by Carsopre** [Deltares/ra2ce#217]

**Comment by mjevanmarle** [comment]
Link this with InterTwin and scope directions based on discussions

**Comment by Carsopre** [comment]
Verified during Intertwin, the results / lessons learnt can be found in its [hackathon jupyter notebook](https://github.com/Deltares/ra2ce/blob/d133861df6b755600947ef50588fd00cdf88d326/examples/hackathons/20240326_hackathon/summary_2024q1.ipynb)
