### ISSUE TITLE
Losses - indirect analysis

### ISSUE THREAD

**Issue by ThomasBles** [Deltares/ra2ce#234]
The following needs to be reviewed in the code and tested:

1. - [x] use of resilience functions
2. - [x] combine resilience function with criticality outcomes to determine vehicle loss hours
3. - [x] determine monetized losses with the concept of Value of Time
4. - [x] Create a test case in a Jupyter Notebook.
> - [ ] 4.1. Explain the steps
> - [ ] 4.2. Include a criticality analysis required for the losses
> - [ ] 4.3. Visualise the main outputs

5. - [x] #326 
6. - [x] #328 
7. - [x] #327 
8. - [x] #350 
9. - [x] #380

**Comment by mjevanmarle** [comment]
[2023-11-24_Sprint_Losses summary.docx](https://github.com/Deltares/ra2ce/files/14401669/2023-11-24_Sprint_Losses.summary.docx)
