### ISSUE TITLE
Store intermediate product when network is broken 

### ISSUE THREAD

**Issue by mjevanmarle** [Deltares/ra2ce#275]
Wrong: When you load until the residential area of the Utrecht area RA2CE downloads the data from OSM, but fails to store it, because of a geometry error (probably due to a disconnection of the residential network). RA2CE gives the error but it is not possible to change the network as such it does work. The intermediate product needs to be stored. It is data related, because it does work for Utrecht up until tertiary_link and it also does work for Amsterdam until residential. Needs to be fixed for future requests. 
How to reproduce: jupyter notebook at Margreets personal drive -> also stored in Margreets Postbox
Expected behavior: The intermediate product should be stored and an error message should be delivered to the user to fix the network. Follow up idea: A brainstorm is needed to fix the networks outside the core.

**Comment by LiekeMeijer** [comment]
I have this same 'key error: geometry' with different data - and roads until tertiary. I will put the data in Margreet's postbox as well.
