### ISSUE TITLE
Linking network and graph for damages

### ISSUE THREAD

**Issue by sahand-asgarpour** [Deltares/ra2ce#355]
The goal is to estimate the damages of each link in the Graph object using the Damages result (estimating the damages for each segment of a Network).

- Graph: graph representing nodes and links
- Network: 100 metre segmented graph

**Comment by ArdtK** [comment]
@sahand-asgarpour could you add some more context to this issue? Things like the goal and some idea on the scope (what needs to be done)?

**Comment by sahand-asgarpour** [comment]
> @sahand-asgarpour could you add some more context to this issue? Things like the goal and some idea on the scope (what needs to be done)?

Description updated
