### ISSUE TITLE
Allow an analysis run without files.

### ISSUE THREAD

**Issue by Carsopre** [Deltares/ra2ce#389]
### Kind of request

Enhancement of current functionality

### Enhancement Description

It should be possible to create a ra2ce run through the ra2ce handler just by providing the `AnalysisConfigData` and / or the `NetworkConfigData`. 

This allows 'scientists' to create their own scripts / jupyter notebooks without having to create any python file.

Currently it is possible to do something similar however the files are still required, example:

```python
_root_dir = Path("/data")
assert _root_dir.exists()

_network_file = _root_dir.joinpath("network.ini")
assert _network_file.exists()

_tif_data_directory = _root_dir.joinpath("static", "hazard")
assert _tif_data_directory.exists()

# Run analysis
_handler = Ra2ceHandler(_network_file, analysis=None)
_handler.input_config.network_config.config_data.hazard.hazard_map = [
    list(_tif_data_directory.glob("*.tif"))[0]
]

_handler.configure()
_handler.run_analysis()
```

### Use case

Given a scientists, that wants to create a running model but does not want to create a file as they work mostly scripting.
- They want full control over the  Network / Analysis `config_data` representation, so they can do iterations over different scenarios.
- They want to be able to run an analysis with a given network and analysis config data __without__ having to initialize wrappers and the other (rather complex) instances.
- They still want tha ra2ce logging.

**Comment by ArdtK** [comment]
Chosen direction: Add a 3rd parameter to the creation of an analysis (`working_dir`) which allows:
* logging to be created even if no ini files are provided;
* only providing the name of the ini files (without path; with path is still allowed);
* trying to find the default ini files if present in the `working_dir`.

Notes:
* If `working_dir` is provided the path to the ini files is ignored; only the name is taken into account.
*
