### ISSUE TITLE
Create notebook with 2024Q1 tech work

### ISSUE THREAD

**Issue by ArdtK** [Deltares/ra2ce#401]
What to do:

- [x] Create a few simple cases of functionality introduced in the last sprints.
  - [x] Modify `.ini` files from code.
  - [x] Using enums.
- [x] Create this jupyter notebook in `/docs/tech_meetings`
  - [x] Tests do not collect the hereby created notebooks.
  - [x] Include these notebook(s) in a new section within the official documentation.

**Comment by Carsopre** [comment]
Tech meetings section can be found under the `technical documentation` chapter of the official ra2ce documentation.
