### ISSUE TITLE
Custom definition of `simplify_graph` limits our `OSMNX` version to 1.7.1

### ISSUE THREAD

**Issue by Carsopre** [Deltares/ra2ce#410]
### Ra2ce version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of Ra2ce in `master` [here](https://github.com/Deltares/ra2ce).

### Reproducible example

Upgrade `osmnx` version in your local environment to 1.9.2 (for instance).
After correctly downloading a network from OSMNX it will fail during the cleaning steps as we wrote our own definition of the `simplify_graph` function in `network_utils` (`ra2ce.network.network_utils::simplify_graph`) which will point to potentially outdated methods.

### Current behaviour

In `ra2ce.network.network_utils.py`:
```python
def simplify_graph(
    graph: nx.Graph, strict: bool, remove_rings: bool, track_merged: bool
):
```

This method is basically a copy & paste (with minor changes) of the original method from `OSMNX`. The main problem here is that we call to internal methods that changed in versions posterior to `1.7.1`. For now it works if we make the `osmnx` version fix to 1.7.1, however this is not the desired behavior.

### Desired behaviour

We do not copy and paste the whole function but rather just make sure we do a proper pre and post processing of the library's methods.

### Additional context

Affects #408

**Comment by ArdtK** [comment]
@sahand-asgarpour it might be worth having a look at this PR to see how I solved your issue.

**Comment by sahand-asgarpour** [comment]
> @sahand-asgarpour it might be worth having a look at this PR to see how I solved your issue.

@ArdtK Nice and clean solution! Thanks.
