### ISSUE TITLE
direct_damage example fails when residential roads are not included

### ISSUE THREAD

**Issue by sahand-asgarpour** [Deltares/ra2ce#435]
### Ra2ce version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of Ra2ce in `master` [here](https://github.com/Deltares/ra2ce).

### Reproducible example

in the example_direct_damage, remove the residential from the road_types of the network.ini.

### Current behaviour

Then direct_damage crashes during the analysis at:
```python
direct_utils

dictionary = dict(gdf.groupby("road_type")["lanes"].agg(pd.Series.mode))
```

### Desired behaviour

**Carles:** Simply log that no information was found for this road type and continue. In addition, try to create a failing test for easiness is issue reproduction.

**Comment by ArdtK** [comment]
Huizinga case

from ra2ce.ra2ce_handler import Ra2ceHandler
from ra2ce.network.network_config_data.network_config_data_reader import NetworkConfigDataReader
from ra2ce.analysis.analysis_config_data.analysis_config_data_reader import AnalysisConfigDataReader

# Load network data.
_network_config_data = NetworkConfigDataReader().read(root_dir.joinpath("network.ini"))
**_road_types = [_rt for _rt in _network_config_data.network.road_types if _rt.name != "RESIDENTIAL"]
_network_config_data.network.road_types = _road_types**

# Load analysis data.
_analysis_config_data = AnalysisConfigDataReader().read(root_dir.joinpath("analysis.ini"))

_analysis_config_data.input_path = root_dir.joinpath("input_analysis_data")
