### ISSUE TITLE
Build and publish Docker containers

### ISSUE THREAD

**Issue by ArdtK** [Deltares/ra2ce#528]
**Goal**
On each push in master build an publish a Docker container in Harbor (https://containers.deltares.nl/harbor/projects/11/repositories).

**Steps**
* Create build step
  * Add ra2ce to the Docker pool in TC - Willem Noorduin
* Create publish step
  * Add robot to the ra2ce project (https://publicwiki.deltares.nl/display/GIT/Harbor+-+Frequently+asked+Questions) - asked Erik de Rooij
 
**Versioning**
* For each push on master, push a container named or tagged "latest"
* For each tagged version, push a container named or tagged after the version

**Comment by Carsopre** [comment]
This issue has been completed and we can now automatically build docker images via TeamCity pipelines.
