### ISSUE TITLE
reprojecting graph does not update the NetwporkX graph crs

### ISSUE THREAD

**Issue by Cham8920** [Deltares/ra2ce#542]
### Ra2ce version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of Ra2ce in `master` [here](https://github.com/Deltares/ra2ce).

### Reproducible example

Damages workflow uses the columns highway(to get road type)  and lanes for the calculations. 
When I used a shp file for the road network (not from osm) the final graph network didn't contain the highway column 

### Current behaviour

I think the problem is here:
 ra2ce\ra2ce\network\network_wrappers\vector_network_wrapper.py line 85,90 to include highways and lanes in the final network
 
        gdf = self._read_vector_to_project_region_and_crs()
        gdf = self.clean_vector(gdf)
        if self.directed:
            graph = self._get_direct_graph_from_vector(
                gdf=gdf, edge_attributes_to_include=["avgspeed", "bridge", "tunnel"]
            )
        else:
            graph = self._get_undirected_graph_from_vector(
                gdf, edge_attributes_to_include=["avgspeed", "bridge", "tunnel"]

### Desired behaviour

It worled when I changed here: 
ra2ce\ra2ce\network\network_wrappers\vector_network_wrapper.py line 85,90 to include highways and lanes in the final network
 
        gdf = self._read_vector_to_project_region_and_crs()
        gdf = self.clean_vector(gdf)
        if self.directed:
            graph = self._get_direct_graph_from_vector(
                gdf=gdf, edge_attributes_to_include=["avgspeed", "bridge", "tunnel"**,"highway","lanes"**]
            )
        else:
            graph = self._get_undirected_graph_from_vector(
                gdf, edge_attributes_to_include=["avgspeed", "bridge", "tunnel",**"highway","lanes"**]

When I did this , it still created a blank column so I made a change to the  \ra2ce\ra2ce\runners\damages_analysis_runner.py in line 131-132 because the blank column gave me some trouble.
 
 event_cols = [
            col
            for col in result_segment_based.columns
            if (len(col) > 1 and col[0].isupper() and col[1] == "_")
            #if (col[0].isupper() and col[1] == "_")
        ]
        events = set([x.split("_")[1] for x in event_cols])  # set of unique event

**Comment by sahand-asgarpour** [comment]
> ### Ra2ce version checks
> 
>     * [x]  I have checked that this issue has not already been reported.
> 
>     * [x]  I have checked that this bug exists on the latest version of Ra2ce in `master` [here](https://github.com/Deltares/ra2ce).
> 
> 
> ### Reproducible example
> 
> Damages workflow uses the columns highway(to get road type) and lanes for the calculations. When I used a shp file for the road network (not from osm) the final graph network didn't contain the highway column
> ### Current behaviour
> 
> I think the problem is here: ra2ce\ra2ce\network\network_wrappers\vector_network_wrapper.py line 85,90 to include highways and lanes in the final network
> 
> ```
>     gdf = self._read_vector_to_project_region_and_crs()
>     gdf = self.clean_vector(gdf)
>     if self.directed:
>         graph = self._get_direct_graph_from_vector(
>             gdf=gdf, edge_attributes_to_include=["avgspeed", "bridge", "tunnel"]
>         )
>     else:
>         graph = self._get_undirected_graph_from_vector(
>             gdf, edge_attributes_to_include=["avgspeed", "bridge", "tunnel"]
> ```
> 
> ### Desired behaviour
> 
> It worled when I changed here: ra2ce\ra2ce\network\network_wrappers\vector_network_wrapper.py line 85,90 to include highways and lanes in the final network
> 
> ```
>     gdf = self._read_vector_to_project_region_and_crs()
>     gdf = self.clean_vector(gdf)
>     if self.directed:
>         graph = self._get_direct_graph_from_vector(
>             gdf=gdf, edge_attributes_to_include=["avgspeed", "bridge", "tunnel"**,"highway","lanes"**]
>         )
>     else:
>         graph = self._get_undirected_graph_from_vector(
>             gdf, edge_attributes_to_include=["avgspeed", "bridge", "tunnel",**"highway","lanes"**]
> ```
> 
> When I did this , it still created a blank column so I made a change to the \ra2ce\ra2ce\runners\damages_analysis_runner.py in line 131-132 because the blank column gave me some trouble.
> 
> event_cols = [ col for col in result_segment_based.columns if (len(col) > 1 and col[0].isupper() and col[1] == "_") #if (col[0].isupper() and col[1] == "_") ] events = set([x.split("_")[1] for x in event_cols]) # set of unique event
> ### Additional context
> 
> _No response_

This is not an error. link_type_column and file_id attributes should be filled in as 'highway' and <id_column>.


Here a commit is pushed that updates the reprojected crs.
