### ISSUE TITLE
Adaptation: create and save result cost options

### ISSUE THREAD

**Issue by MatthiasHauthDeltares** [Deltares/ra2ce#594]
** Requirements
- the total cost of the AdaptationOption (https://github.com/Deltares/ra2ce/issues/593)
- a network without overlay.

## outputs
return a GeoPackage file called `cost_adaptation_option.gpkg` based on the network with a new column for every AdaptationOption defined.
The new columns should have as name: `costs_option_{OPTION_ID}`

**Comment by ArdtK** [comment]
@MatthiasHauthDeltares this needs a network **with** overlay, right?
Should this also contain a calculation as unit_cost * length * fraction per link?
