### ISSUE TITLE
Create design of setup of orchestrator

### ISSUE THREAD

**Issue by ArdtK** [Deltares/ra2ce#602]
**Goal**
Find out how we can run all sub-analyses for the AOs (Damages, Losses, Cost) and aggregating the results in the finals step.

**Options**
A. Doing everything sequentially with the adaptation analysis calling the sub-analyses with their respective configs
B. Having an orchestrator that runs the sub-analyses as separate steps

**Suggestion**
Check with FloodAdapt how it works there

**Comment by Carsopre** [comment]
Design has been submitted and follow-up (epic) issue has been created [#662](https://github.com/Deltares/ra2ce/issues/662)
