### ISSUE TITLE
Adaptation: add option to Adaptation config to calculate cost based on fraction segment exposed

### ISSUE THREAD

**Issue by MatthiasHauthDeltares** [Deltares/ra2ce#618]
### Kind of request

None

### Enhancement Description

Add a (boolean) argument to the Adaptation config for the user to decide if the cost should be calculated on the full length of the link or from the exposed segments:

-  If the cost is calculated from the full length of the link; Just multiply the unit present unit cost of the adaptation option to the length of the link and add it to gdf.

- If the cost is calculated from the exposed fraction: this is more complicated: 

1.  Fetch the network with hazard overlay
2. multiply the net present value unit cost of the adaptation option to the length of the link, multiply again by the fraction of the hazard.
3. Aggregate the cost per link (sum the cost for all the segments of a link)
4. add it to gdf

In either case, the final gdf should have a column "cost_AO{id}" for every adaptation option

**Comment by ArdtK** [comment]
Discussed with @MatthiasHauthDeltares : the (unsegmented) network (GeoDataFrame) with overlay is sufficient. It will yield the same result as calculating it on the segmented graph (MultiGraph) and then consolidating it to the unsegmented network.
