### ISSUE TITLE
[Bolivia branch]: general 

### ISSUE THREAD

**Issue by xldeltares** [Deltares/ra2ce#71]
Reminders of issues that needs to be discussed within the Bolivia project:
- [ ] future warnings
- [ ] Fiona laundries the .shp columns
- [ ] documentation of what the output columns stands for and how to interpret them
- [x] if the network graph is not fully connected, how does it impact the analysis?
- [x] In the code it is still called cut_at_intersections, while in doc it states ignore_intersections --> should be cut_at_intersections

**Comment by Carsopre** [comment]
@frederique-hub  please create follow-up (concrete) issues if needed I am closing this one as the bolivia branch was already integrated.

**Comment by frederique-hub** [comment]
Sure!
