### ISSUE TITLE
Error in handler that loads existing base_graph_hazard

### ISSUE THREAD

**Issue by keesvanginkel** [Deltares/ra2ce#82]
Error in handler causes error in analyses_direct.py line 87
Under these conditions:

- hazard overlay **with graph AND network** has already been done in an earlier ra2ce run
- ra2ce is restarted to do damage calculation
- the base_network_hazard.feather discovered (ra2ce log: 2023-01-13 02:05:57 PM - [network_config.py:95] - root - INFO - Existing graph/network found: D:\Python\ra2ce\data\91_OSdaMage_EAD\static\output_graph\base_network_hazard.feather.
2) 
The key **base_network_hazard** is completely missing in DirectAnalyses.graphs, while the other keys are present (including the base_graph_hazard).

**Comment by Carsopre** [comment]
Issue misses reproduction steps as well as desired behavior. Most likely has also been fixed during the past releases as we are now handling the reuse of existing network files.
